// AUTO-GENERATED by scripts/build-manual-index.ts. Do not edit by hand.
// Re-run `npm run prebuild` to regenerate.

import type { ManualManifest } from "@/lib/manual/types";

export const manualManifest: ManualManifest = {
  "generatedAt": "2026-05-23T10:56:43.955Z",
  "sections": [
    {
      "id": "getting-started",
      "order": 0,
      "title": "Getting Started",
      "summary": "What this platform is and how to sign in.",
      "primaryAudience": "both",
      "path": "/help/getting-started",
      "topics": [
        {
          "slug": "welcome",
          "title": "Welcome to FPL Tracker",
          "audience": "both",
          "summary": "A 60-second tour of what this app is, what your league lives on it, and where to look first.",
          "lastUpdated": "2026-05-18",
          "path": "/help/getting-started/welcome",
          "sectionId": "getting-started",
          "sectionTitle": "Getting Started",
          "order": 1,
          "wordCount": 370,
          "featurePagePath": null,
          "relatedTopics": [
            "/help/getting-started/magic-link",
            "/help/getting-started/switching-leagues"
          ]
        },
        {
          "slug": "magic-link",
          "title": "Signing in with a magic-link",
          "audience": "both",
          "summary": "There are no passwords. Enter your email, click the link we send you, and you're in.",
          "lastUpdated": "2026-05-18",
          "path": "/help/getting-started/magic-link",
          "sectionId": "getting-started",
          "sectionTitle": "Getting Started",
          "order": 2,
          "wordCount": 372,
          "featurePagePath": null,
          "relatedTopics": [
            "/help/getting-started/troubleshooting-sign-in",
            "/help/getting-started/accepting-an-invitation"
          ]
        },
        {
          "slug": "switching-leagues",
          "title": "Switching between leagues",
          "audience": "both",
          "summary": "If you're in more than one league, the League Switcher at the top of the sidebar moves you between them while keeping your context.",
          "lastUpdated": "2026-05-18",
          "path": "/help/getting-started/switching-leagues",
          "sectionId": "getting-started",
          "sectionTitle": "Getting Started",
          "order": 3,
          "wordCount": 280,
          "featurePagePath": "/leagues",
          "relatedTopics": [
            "/help/getting-started/welcome"
          ]
        },
        {
          "slug": "accepting-an-invitation",
          "title": "Accepting an invitation",
          "audience": "both",
          "summary": "You received an invitation email from your league admin. Here's what to do with it.",
          "lastUpdated": "2026-05-18",
          "path": "/help/getting-started/accepting-an-invitation",
          "sectionId": "getting-started",
          "sectionTitle": "Getting Started",
          "order": 4,
          "wordCount": 317,
          "featurePagePath": null,
          "relatedTopics": [
            "/help/getting-started/magic-link"
          ]
        },
        {
          "slug": "troubleshooting-sign-in",
          "title": "Troubleshooting sign-in",
          "audience": "both",
          "summary": "The magic-link didn't arrive, or arrived and didn't work. Here's the checklist.",
          "lastUpdated": "2026-05-18",
          "path": "/help/getting-started/troubleshooting-sign-in",
          "sectionId": "getting-started",
          "sectionTitle": "Getting Started",
          "order": 5,
          "wordCount": 522,
          "featurePagePath": null,
          "relatedTopics": [
            "/help/getting-started/magic-link"
          ]
        }
      ]
    },
    {
      "id": "reading-the-app",
      "order": 10,
      "title": "Reading the App",
      "summary": "Every analytics and standings page, explained.",
      "primaryAudience": "member",
      "path": "/help/reading-the-app",
      "topics": [
        {
          "slug": "standings",
          "title": "Standings",
          "audience": "member",
          "summary": "The home leaderboard. Total points, gameweek points, rank, and rank-change for every member of your league.",
          "lastUpdated": "2026-05-18",
          "path": "/help/reading-the-app/standings",
          "sectionId": "reading-the-app",
          "sectionTitle": "Reading the App",
          "order": 1,
          "wordCount": 452,
          "featurePagePath": "/l/[leagueSlug]/standings",
          "relatedTopics": [
            "/help/reading-the-app/live-points",
            "/help/reading-the-app/form-table"
          ]
        },
        {
          "slug": "live-points",
          "title": "Live Points",
          "audience": "member",
          "summary": "Mid-gameweek tracker. Every manager's live score updated as fixtures play out.",
          "lastUpdated": "2026-05-18",
          "path": "/help/reading-the-app/live-points",
          "sectionId": "reading-the-app",
          "sectionTitle": "Reading the App",
          "order": 2,
          "wordCount": 380,
          "featurePagePath": "/l/[leagueSlug]/live",
          "relatedTopics": [
            "/help/reading-the-app/standings",
            "/help/reading-the-app/captain-history"
          ]
        },
        {
          "slug": "transfers",
          "title": "Transfers",
          "audience": "member",
          "summary": "Who bought and sold whom, when, and how many hits they took to do it.",
          "lastUpdated": "2026-05-18",
          "path": "/help/reading-the-app/transfers",
          "sectionId": "reading-the-app",
          "sectionTitle": "Reading the App",
          "order": 3,
          "wordCount": 347,
          "featurePagePath": "/l/[leagueSlug]/transfers",
          "relatedTopics": [
            "/help/reading-the-app/regret"
          ]
        },
        {
          "slug": "form-table",
          "title": "Form Table",
          "audience": "member",
          "summary": "Last-three-gameweek momentum, with inline sparklines showing whose trend is real.",
          "lastUpdated": "2026-05-18",
          "path": "/help/reading-the-app/form-table",
          "sectionId": "reading-the-app",
          "sectionTitle": "Reading the App",
          "order": 4,
          "wordCount": 329,
          "featurePagePath": "/l/[leagueSlug]/form",
          "relatedTopics": [
            "/help/reading-the-app/standings",
            "/help/reading-the-app/season-stats"
          ]
        },
        {
          "slug": "season-stats",
          "title": "Season Stats",
          "audience": "member",
          "summary": "League-wide cumulative numbers — total bench wasted, total transfer hits, total captain blanks, and more.",
          "lastUpdated": "2026-05-18",
          "path": "/help/reading-the-app/season-stats",
          "sectionId": "reading-the-app",
          "sectionTitle": "Reading the App",
          "order": 5,
          "wordCount": 334,
          "featurePagePath": "/l/[leagueSlug]/season-stats",
          "relatedTopics": []
        },
        {
          "slug": "bench-waste",
          "title": "Bench Waste",
          "audience": "member",
          "summary": "A manager-by-gameweek heatmap of points left rotting on your bench.",
          "lastUpdated": "2026-05-18",
          "path": "/help/reading-the-app/bench-waste",
          "sectionId": "reading-the-app",
          "sectionTitle": "Reading the App",
          "order": 6,
          "wordCount": 341,
          "featurePagePath": "/l/[leagueSlug]/bench",
          "relatedTopics": [
            "/help/reading-the-app/season-stats",
            "/help/reading-the-app/agony"
          ]
        },
        {
          "slug": "captain-history",
          "title": "Captain History",
          "audience": "member",
          "summary": "Every captain pick from every manager across every gameweek, colour-coded by points.",
          "lastUpdated": "2026-05-18",
          "path": "/help/reading-the-app/captain-history",
          "sectionId": "reading-the-app",
          "sectionTitle": "Reading the App",
          "order": 7,
          "wordCount": 296,
          "featurePagePath": "/l/[leagueSlug]/captain-history",
          "relatedTopics": [
            "/help/reading-the-app/captain-whatif",
            "/help/reading-the-app/wall-of-shame"
          ]
        },
        {
          "slug": "h2h",
          "title": "H2H Battle Simulator",
          "audience": "member",
          "summary": "Pit any two managers against each other in any gameweek and see who would have won.",
          "lastUpdated": "2026-05-18",
          "path": "/help/reading-the-app/h2h",
          "sectionId": "reading-the-app",
          "sectionTitle": "Reading the App",
          "order": 8,
          "wordCount": 318,
          "featurePagePath": "/l/[leagueSlug]/h2h",
          "relatedTopics": []
        },
        {
          "slug": "regret",
          "title": "Transfer Regret",
          "audience": "member",
          "summary": "For every transfer, the player you sold, the player you bought, and the points difference that followed.",
          "lastUpdated": "2026-05-18",
          "path": "/help/reading-the-app/regret",
          "sectionId": "reading-the-app",
          "sectionTitle": "Reading the App",
          "order": 9,
          "wordCount": 375,
          "featurePagePath": "/l/[leagueSlug]/regret",
          "relatedTopics": [
            "/help/reading-the-app/transfers"
          ]
        },
        {
          "slug": "agony",
          "title": "Agony Index",
          "audience": "member",
          "summary": "A composite misfortune score that rolls bench waste, transfer hits, captain blanks, and gameweek suffering into a single leaderboard nobody wants to top.",
          "lastUpdated": "2026-05-18",
          "path": "/help/reading-the-app/agony",
          "sectionId": "reading-the-app",
          "sectionTitle": "Reading the App",
          "order": 10,
          "wordCount": 332,
          "featurePagePath": "/l/[leagueSlug]/agony",
          "relatedTopics": [
            "/help/reading-the-app/bench-waste",
            "/help/reading-the-app/regret"
          ]
        },
        {
          "slug": "luck",
          "title": "Luck Ranking",
          "audience": "member",
          "summary": "Separates skill from luck by comparing your actual gameweek scores to a model of what you \"should\" have scored.",
          "lastUpdated": "2026-05-18",
          "path": "/help/reading-the-app/luck",
          "sectionId": "reading-the-app",
          "sectionTitle": "Reading the App",
          "order": 11,
          "wordCount": 415,
          "featurePagePath": "/l/[leagueSlug]/luck",
          "relatedTopics": []
        },
        {
          "slug": "captain-whatif",
          "title": "Captain What-If",
          "audience": "member",
          "summary": "For every gameweek, what your captain scored vs. the best captain you could have picked from your own squad.",
          "lastUpdated": "2026-05-18",
          "path": "/help/reading-the-app/captain-whatif",
          "sectionId": "reading-the-app",
          "sectionTitle": "Reading the App",
          "order": 12,
          "wordCount": 319,
          "featurePagePath": "/l/[leagueSlug]/captain-whatif",
          "relatedTopics": [
            "/help/reading-the-app/captain-history"
          ]
        },
        {
          "slug": "wall-of-shame",
          "title": "Wall of Shame",
          "audience": "member",
          "summary": "Six permanent trophy cards for the season's most spectacular failures, updated every gameweek.",
          "lastUpdated": "2026-05-18",
          "path": "/help/reading-the-app/wall-of-shame",
          "sectionId": "reading-the-app",
          "sectionTitle": "Reading the App",
          "order": 13,
          "wordCount": 401,
          "featurePagePath": "/l/[leagueSlug]/wall-of-shame",
          "relatedTopics": []
        },
        {
          "slug": "fixtures",
          "title": "Fixtures",
          "audience": "member",
          "summary": "The next five gameweeks of fixtures, sorted by team, with FPL difficulty ratings and live scores.",
          "lastUpdated": "2026-05-18",
          "path": "/help/reading-the-app/fixtures",
          "sectionId": "reading-the-app",
          "sectionTitle": "Reading the App",
          "order": 14,
          "wordCount": 343,
          "featurePagePath": "/l/[leagueSlug]/fixtures",
          "relatedTopics": []
        },
        {
          "slug": "ownership",
          "title": "Ownership",
          "audience": "member",
          "summary": "For every player owned by anyone in your league, how many of your managers own them.",
          "lastUpdated": "2026-05-18",
          "path": "/help/reading-the-app/ownership",
          "sectionId": "reading-the-app",
          "sectionTitle": "Reading the App",
          "order": 15,
          "wordCount": 387,
          "featurePagePath": "/l/[leagueSlug]/ownership",
          "relatedTopics": [
            "/help/reading-the-app/differentials"
          ]
        },
        {
          "slug": "differentials",
          "title": "Differential Alerts",
          "audience": "member",
          "summary": "Low-owned players who scored big in the most recent gameweek — the players that decided the GW.",
          "lastUpdated": "2026-05-18",
          "path": "/help/reading-the-app/differentials",
          "sectionId": "reading-the-app",
          "sectionTitle": "Reading the App",
          "order": 16,
          "wordCount": 352,
          "featurePagePath": "/l/[leagueSlug]/differentials",
          "relatedTopics": [
            "/help/reading-the-app/ownership"
          ]
        },
        {
          "slug": "injuries",
          "title": "Injuries",
          "audience": "member",
          "summary": "A list of every player owned by anyone in your league who has a non-100% chance of playing.",
          "lastUpdated": "2026-05-18",
          "path": "/help/reading-the-app/injuries",
          "sectionId": "reading-the-app",
          "sectionTitle": "Reading the App",
          "order": 17,
          "wordCount": 387,
          "featurePagePath": "/l/[leagueSlug]/player-status",
          "relatedTopics": []
        }
      ]
    },
    {
      "id": "league-admin",
      "order": 20,
      "title": "League Admin",
      "summary": "Everything you need to administer a league.",
      "primaryAudience": "admin",
      "path": "/help/league-admin",
      "topics": [
        {
          "slug": "overview",
          "title": "League Admin overview",
          "audience": "admin",
          "summary": "What you can do as a League Admin, where it lives in the app, and the order to learn things in.",
          "lastUpdated": "2026-05-18",
          "path": "/help/league-admin/overview",
          "sectionId": "league-admin",
          "sectionTitle": "League Admin",
          "order": 1,
          "wordCount": 382,
          "featurePagePath": "/l/[leagueSlug]/admin/settings",
          "relatedTopics": [
            "/help/league-admin/league-settings",
            "/help/league-admin/inviting-members",
            "/help/league-admin/weekly-digest"
          ]
        },
        {
          "slug": "league-settings",
          "title": "League settings",
          "audience": "admin",
          "summary": "Name, slug, logo, mini-league ID, digest prompt — every league-level configuration the platform exposes.",
          "lastUpdated": "2026-05-18",
          "path": "/help/league-admin/league-settings",
          "sectionId": "league-admin",
          "sectionTitle": "League Admin",
          "order": 2,
          "wordCount": 455,
          "featurePagePath": "/l/[leagueSlug]/admin/settings",
          "relatedTopics": [
            "/help/league-admin/syncing-members",
            "/help/league-admin/weekly-digest"
          ]
        },
        {
          "slug": "syncing-members",
          "title": "Syncing members from FPL",
          "audience": "admin",
          "summary": "Pull your FPL mini-league's roster into the app in one click. Re-run whenever members come or go.",
          "lastUpdated": "2026-05-18",
          "path": "/help/league-admin/syncing-members",
          "sectionId": "league-admin",
          "sectionTitle": "League Admin",
          "order": 3,
          "wordCount": 416,
          "featurePagePath": "/l/[leagueSlug]/admin/members",
          "relatedTopics": [
            "/help/league-admin/league-settings",
            "/help/league-admin/inviting-members"
          ]
        },
        {
          "slug": "inviting-members",
          "title": "Inviting members by email",
          "audience": "admin",
          "summary": "Send a single-use magic-link to a new member so they can accept and sign in.",
          "lastUpdated": "2026-05-18",
          "path": "/help/league-admin/inviting-members",
          "sectionId": "league-admin",
          "sectionTitle": "League Admin",
          "order": 4,
          "wordCount": 550,
          "featurePagePath": "/l/[leagueSlug]/admin/members",
          "relatedTopics": [
            "/help/league-admin/editing-members",
            "/help/getting-started/accepting-an-invitation"
          ]
        },
        {
          "slug": "editing-members",
          "title": "Editing members",
          "audience": "admin",
          "summary": "Update a member's display name, team name, email, or points deduction. Remove or reactivate members.",
          "lastUpdated": "2026-05-18",
          "path": "/help/league-admin/editing-members",
          "sectionId": "league-admin",
          "sectionTitle": "League Admin",
          "order": 5,
          "wordCount": 533,
          "featurePagePath": "/l/[leagueSlug]/admin/members",
          "relatedTopics": []
        },
        {
          "slug": "weekly-digest",
          "title": "Sending the weekly digest",
          "audience": "admin",
          "summary": "Trigger a GW-summary email to every member with a configured email address.",
          "lastUpdated": "2026-05-18",
          "path": "/help/league-admin/weekly-digest",
          "sectionId": "league-admin",
          "sectionTitle": "League Admin",
          "order": 6,
          "wordCount": 685,
          "featurePagePath": "/l/[leagueSlug]/admin/digest",
          "relatedTopics": [
            "/help/league-admin/league-settings",
            "/help/league-admin/editing-members"
          ]
        },
        {
          "slug": "audit-log",
          "title": "Audit log",
          "audience": "admin",
          "summary": "Every administrative action in your league, who did it, and when. Read-only.",
          "lastUpdated": "2026-05-18",
          "path": "/help/league-admin/audit-log",
          "sectionId": "league-admin",
          "sectionTitle": "League Admin",
          "order": 7,
          "wordCount": 503,
          "featurePagePath": "/l/[leagueSlug]/admin/audit",
          "relatedTopics": []
        },
        {
          "slug": "suspended-league",
          "title": "When a league is suspended",
          "audience": "admin",
          "summary": "What you and your members see when a Super Admin suspends the league, and what happens to your data.",
          "lastUpdated": "2026-05-18",
          "path": "/help/league-admin/suspended-league",
          "sectionId": "league-admin",
          "sectionTitle": "League Admin",
          "order": 8,
          "wordCount": 484,
          "featurePagePath": null,
          "relatedTopics": []
        }
      ]
    }
  ]
};
