// AUTO-GENERATED by scripts/build-manual-index.ts. Do not edit by hand.
// Re-run `npm run prebuild` to regenerate.

import type { ComponentType } from "react";

export type ManualModuleLoader = () => Promise<{ default: ComponentType }>;

export const manualModules: Record<string, ManualModuleLoader> = {
  "/help/getting-started/welcome": () => import("./00-getting-started/01-welcome.mdx"),
  "/help/getting-started/magic-link": () => import("./00-getting-started/02-magic-link.mdx"),
  "/help/getting-started/switching-leagues": () => import("./00-getting-started/03-switching-leagues.mdx"),
  "/help/getting-started/accepting-an-invitation": () => import("./00-getting-started/04-accepting-an-invitation.mdx"),
  "/help/getting-started/troubleshooting-sign-in": () => import("./00-getting-started/05-troubleshooting-sign-in.mdx"),
  "/help/reading-the-app/standings": () => import("./10-reading-the-app/01-standings.mdx"),
  "/help/reading-the-app/live-points": () => import("./10-reading-the-app/02-live-points.mdx"),
  "/help/reading-the-app/transfers": () => import("./10-reading-the-app/03-transfers.mdx"),
  "/help/reading-the-app/form-table": () => import("./10-reading-the-app/04-form-table.mdx"),
  "/help/reading-the-app/season-stats": () => import("./10-reading-the-app/05-season-stats.mdx"),
  "/help/reading-the-app/bench-waste": () => import("./10-reading-the-app/06-bench-waste.mdx"),
  "/help/reading-the-app/captain-history": () => import("./10-reading-the-app/07-captain-history.mdx"),
  "/help/reading-the-app/h2h": () => import("./10-reading-the-app/08-h2h.mdx"),
  "/help/reading-the-app/regret": () => import("./10-reading-the-app/09-regret.mdx"),
  "/help/reading-the-app/agony": () => import("./10-reading-the-app/10-agony.mdx"),
  "/help/reading-the-app/luck": () => import("./10-reading-the-app/11-luck.mdx"),
  "/help/reading-the-app/captain-whatif": () => import("./10-reading-the-app/12-captain-whatif.mdx"),
  "/help/reading-the-app/wall-of-shame": () => import("./10-reading-the-app/13-wall-of-shame.mdx"),
  "/help/reading-the-app/fixtures": () => import("./10-reading-the-app/14-fixtures.mdx"),
  "/help/reading-the-app/ownership": () => import("./10-reading-the-app/15-ownership.mdx"),
  "/help/reading-the-app/differentials": () => import("./10-reading-the-app/16-differentials.mdx"),
  "/help/reading-the-app/injuries": () => import("./10-reading-the-app/17-injuries.mdx"),
  "/help/league-admin/overview": () => import("./20-league-admin/01-overview.mdx"),
  "/help/league-admin/league-settings": () => import("./20-league-admin/02-league-settings.mdx"),
  "/help/league-admin/syncing-members": () => import("./20-league-admin/03-syncing-members.mdx"),
  "/help/league-admin/inviting-members": () => import("./20-league-admin/04-inviting-members.mdx"),
  "/help/league-admin/editing-members": () => import("./20-league-admin/05-editing-members.mdx"),
  "/help/league-admin/weekly-digest": () => import("./20-league-admin/06-weekly-digest.mdx"),
  "/help/league-admin/audit-log": () => import("./20-league-admin/07-audit-log.mdx"),
  "/help/league-admin/suspended-league": () => import("./20-league-admin/08-suspended-league.mdx"),
};
